config/routes.rb
CommonApp::Application.routes.draw do

  root 'cms#index'

    resources :cms do
      collection do
        get 'about'
      end
    end

      match '/admin',  to: 'admin/user_sessions#new',         via: 'get'
      match '/signout', to: 'admin/user_sessions#destroy',     via: 'delete'
      namespace :admin do
      resources :users
      resources :user_sessions, only: [:new, :create, :destroy]
    end
end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password
	before_save { self.email = email.downcase }
	validates :name, presence: true
	validates :name,  presence: true, length: { maximum: 50 }
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
    validates :password, length: { minimum: 6 }
end

app/controllers/admin/user_sessions_controller.rb
class Admin::UserSessionsController < ApplicationController

layout "login"
  def new
  end

  def create
  user = User.find_by(email: params[:user_session][:email].downcase)
  if user && user.authenticate(params[:user_session][:password])

  	if params[:remember_me]
        cookies.permanent[:user_id] = user.id
      else
        cookies[:user_id] = user.id  
      end
      redirect_to admin_users_path, notice: "Logged in!"
    # Sign the user in and redirect to the user's show page.
  else
     flash[:error] = 'Invalid email/password combination' # Not quite right!
      render 'new'
  end
  end

  def destroy
  	cookies.delete(cookies[:user_id])
    cookies[:user_id] = nil
    redirect_to admin_url, notice: "Logged out!"
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
	before_filter :require_user
	layout "admin"
	

	def index
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user

  def require_user
    redirect_to admin_url if current_user.nil?
  end

  def tab_name
    params[:controller]    
  end

  private
    def current_user
      @current_user ||= User.find_by_id(cookies[:user_id]) if cookies[:user_id]
    end
end

app/controllers/cms_controller.rb
class CmsController < ApplicationController

	def index
	end
	def about
	end
end

app/helpers/admin/user_helper.rb
module Admin::UserHelper
end

app/helpers/admin/user_sessions_helper.rb
module Admin::UserSessionsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cms_helper.rb
module CmsHelper
end

app/views/admin/user_sessions/new.html.erb
<% provide(:title, "Sign in") %>
<div class="test">Sign in</div>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(:user_session, url: admin_user_sessions_path) do |f| %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.submit "Sign in", class: "btn btn-large btn-primary" %>
    <% end %>

  </div>
</div>

app/views/admin/users/index.html.erb
<div class="test">User informartion</div>
<%= link_to "Sign out", signout_path, method: "delete" %>

app/views/cms/about.html.erb
<div class="test">about page</div>

app/views/cms/index.html.erb
<div class="test">client pages </div>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CommonApp</title>
  <%= stylesheet_link_tag    "admin/custom", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
   <header>
     thota header
    </header>
    <main role="main">
       <%= yield %>
    </main>
    <footer>
    	Thota footer
    </footer>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CommonApp</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<header>
     client header
    </header>
    <main role="main">
       <%= yield %>
    </main>
    <footer>
    	client footer
    </footer>
</body>
</html>

app/views/layouts/login.html.erb
<%= yield %>